# Generated by Django 3.1.12 on 2022-08-19 06:13

from django.db import migrations
import djongo.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_settings',
            field=djongo.models.fields.ArrayField(model_container=users.models.DisplaySetting, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='searches',
            field=djongo.models.fields.ArrayField(model_container=users.models.RecentSearch, null=True),
        ),
    ]
