# Generated by Django 3.1.12 on 2022-08-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220819_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
