version: '3.8'

services:
  web:
    build: ./stocks_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./stocks_backend:/usr/src/stocks_backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env
