# Generated by Django 4.0.6 on 2022-08-12 20:43

import dividends_info.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('dividends', djongo.models.fields.ArrayField(model_container=dividends_info.models.Dividend)),
            ],
        ),
    ]
