# Generated by Django 3.1.12 on 2022-08-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dividends_info', '0002_auto_20220814_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='last_updated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
